### ISSUE TITLE
error

### ISSUE THREAD

**Issue by soupnatzi** [xillwillx/skiptracer#11]
[X] Failed at importing tqdm from tdqm: No module named tqdm

Traceback (most recent call last):
  File "skiptracer.py", line 16, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/root/skiptracer/plugins/haveibeenpwned.py", line 14, in <module>
    import cfscrape
ImportError: No module named cfscrape

i have both cfscrape and tdqm installed i am running kali linux amd64

**Comment by subinacls** [comment]
Please try the latest version offered. We had some issues in the previous versions with Python2/3
Please ensure you are using python2 to launch ./skiptracer.py
