### ISSUE TITLE
Nothing work on email and you keep closing issue...

### ISSUE THREAD

**Issue by iNoSec** [xillwillx/skiptracer#15]
Hello it's me!!! again and again!! 

Like i previously said the advanced background in the previous version run forever and now with the change dont run at all, Skiptracer cant acces HaveIBeenPwn, LinkedIn when we say yes to enter credentials it keep going without asking for enter them, and WhoIsMind just ask for Enter and stop... 
So nothing work lol except maybe MySpace but i dont look the packet send because of others issue and MySpace i dont care..

**Comment by xillwillx** [comment]
working on some updates this week, have to remove whoismind because they changed to a paid service called whoisamped, will fix the linkedin credential storage issue.

**Comment by xillwillx** [comment]
new code out, released for bsidesCT talk on saturday but advancedbackgroundchecks added some more crap to detect us, other than that everything else works
