### ISSUE TITLE
not working [HELP]

### ISSUE THREAD

**Issue by deadfishhackers** [xillwillx/skiptracer#18]
**Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/root/skiptracer/plugins/menus.py", line 19, in <module>
    from plugins.reporter import ReportGenerator
  File "/root/skiptracer/plugins/reporter.py", line 1, in <module>
    from docx import Document
ImportError: No module named docx**
*And yes i did ``pip install -r requirements.txt`` but it still doesnt*

**Comment by subinacls** [comment]
python-docx and docx are not the same - 

please install python-docx on your system

as shown below:

root@lab2:/mnt/pwdb/books# pip install python-docx
Collecting python-docx
  Downloading https://files.pythonhosted.org/packages/00/ed/dc8d859eb32980ccf0e5a9b1ab3311415baf55de208777d85826a7fb0b65/python-docx-0.8.7.tar.gz (5.4MB)
    100% |████████████████████████████████| 5.4MB 333kB/s
Collecting lxml>=2.3.2 (from python-docx)
  Downloading https://files.pythonhosted.org/packages/e5/14/f4343239f955442da9da1919a99f7311bc5627522741bada61b2349c8def/lxml-4.2.5-cp27-cp27mu-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.8MB 332kB/s
Building wheels for collected packages: python-docx
  Running setup.py bdist_wheel for python-docx ... done
  Stored in directory: /root/.cache/pip/wheels/c2/c7/a7/4cb54d79bf82f9bb4be1780647700f7ec311f0f98a7a017c17
Successfully built python-docx
Installing collected packages: lxml, python-docx
Successfully installed lxml-4.2.5 python-docx-0.8.7
root@lab2:/mnt/pwdb/books# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from docx import Document
>>>

notice no error ?

**Comment by deadfishhackers** [comment]
I fixed it
