### ISSUE TITLE
New additions

### ISSUE THREAD

**Issue by PaganGuy** [xillwillx/skiptracer#19]
I would love to see the addition of Twitter and Facebook checks.

**Comment by subinacls** [comment]
we are currently moving the Twitter and Facebook modules to a stand alone project. Additionally they will be re-united with the project in the next Major version release. Thanks for the feedback, hope you will enjoy Skiptracer-NG

**Comment by PaganGuy** [comment]
Man you guys rock! I look forward to the next major release. I love skiptracer, use it as an important tool with all my recon and recommend it to all my students. In fact, I am making a tutorial for how to use it on my site using Parrot Security. Feel free to stop by! majikcat.com Keep up the great work!
