### ISSUE TITLE
[6] Domain - Search targets by Domain

### ISSUE THREAD

**Issue by Fultos** [xillwillx/skiptracer#21]
This option does not works

everything else works when any options or  domain is chosen "[?]  crt.sh" flashes, than disapered without results or errors.

**Comment by whoot** [comment]
+1

**Comment by rpigu-i** [comment]
Can you please refer to the Python 3.x branch going forward. All bugs and new development is taking place there. It's still in progress, but known issues can be addressed during the re-write/upgrade process.

Thanks.
