### ISSUE TITLE
Cannot import Document

### ISSUE THREAD

**Issue by vinnytroia** [xillwillx/skiptracer#24]
Docx module is installed, but i still get this error. 

Thoughts?

Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/opt/skiptracer/plugins/menus.py", line 19, in <module>
    from plugins.reporter import ReportGenerator
  File "/opt/skiptracer/plugins/reporter.py", line 1, in <module>
    from docx import Document
ImportError: cannot import name Document

**Comment by vinnytroia** [comment]
If i try to do pip install -r requirements.txt --upgrade, i get this error: 

Collecting ipdb (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/6d/43/c3c2e866a8803e196d6209595020a4a6db1a3c5d07c01455669497ae23d0/ipdb-0.12.tar.gz
    Complete output from command python setup.py egg_info:
    /usr/lib64/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    error in ipdb setup command: Invalid environment marker: python_version >= "3.4"

**Comment by vinnytroia** [comment]
when running in Ubuntu, i get this: 

Failed building wheel for python-docx
  Running setup.py clean for python-docx
Failed to build python-docx
goofile 1.6 has requirement requests==2.13.0, but you'll have requests 2.22.0 which is incompatible.


So i go back and pip install requests==2.13.0, which installs 2.13.0, but i still get the same issue.

**Comment by vinnytroia** [comment]
nevermind, i fixed it. i needed to install setuptools

 pip install -U setuptools

**Comment by LanceLake** [comment]
If you have a working copy, any chance you can send me a copy of the files
(or create a branch here I can pull from) with a list of the commands that
I need to type in to make it work? I've been pulling my hair out to make
this work and all my requirements.txt is loaded.

C:\Users\Joseph\Desktop\Applications\skiptracer-master>python skiptracer.py
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File
"C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\menus.py",
line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File
"C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\fouroneone_info.py",
line 5, in <module>
    from plugins.base import PageGrabber
  File
"C:\Users\Joseph\Desktop\Applications\skiptracer-master\plugins\base.py",
line 4, in <module>
    import requests
ImportError: No module named requests

I'm at my wits end here and if you can help, it would be greatly
appreciated. :)

**Comment by xillwillx** [comment]
pulling hair for two months? https://github.com/xillwillx/skiptracer/issues/22

**Comment by LanceLake** [comment]
Off and on, yes.
