### ISSUE TITLE
Just wondering where this is going?  I could contribute a good bit if I knew others would be actively contributing.

### ISSUE THREAD

**Issue by jump3r34** [xillwillx/skiptracer#25]
This idea is a great idea, however, I see a few areas that would need brushing up to make this a more broad-reaching library, with valid upkeep:

1. Better documentation on the readme - as well as documentation that is overly abundant in each class/method (this is the original thing that was partially 'offputting' to me when I installed this earlier today and was seeing if I could get it to work in a more enterprise manner, the thing that saved it was the structure is there for something that could be truly amazing)

2. It is not compatible with python3 (specifically 3.6+) - people with newer systems and undertaking new apps will not be keen on reverse porting to 2.7

3. [Selenium Module]: New websites JS requirements [BIG DEAL] - Needs a configured directory with selenium, chromedriver, firefox, etc. so the JS can be fired when a site is known to require page loads and user-actions

4. A well-functioning, cmd line API/documentation, so larger users (ones that would contribute more) can make batch calls without needing the UI menu (maybe this is already in play, but I could not tell a format or key/value system for injecting required information when I was looking)

5. Future, long-term: If this ever did grow into something much larger async processing of requests, I can just see this thing screeching to a stop if it fires multiple scrapers in a procedural manner, if in that instance they could all be working at the same time.  

If the group/community wants to go forward with this, it is a good looking library, but to take it to the next level would require some serious input and structure.

If there is a group of guys who is willing to do that, I will be a contributor as well.

**Comment by jump3r34** [comment]
Oh yeah, I am in the legal industry, if some other modules were added(which utilized any number of data sources and scraping techniques, or jurisdictions), the license would likely need to be changed.

**Comment by rpigu-i** [comment]
Hey there - I am actively working on the Python 3 branch in my spare time.

I just updated the readme this morning, so take a look!

**Comment by rpigu-i** [comment]
Also - agree on the procedural approach. For now, let's get the Python 3 branch stable and configurable. 

Once this is done, here is a thought: each of the plugins could be broken out into separate containers. Skiptracer can then add as the orchestrator for each container call them when it wants to run a scan. Results could then be put on a message queue and sent back to Skiptracer.

**Comment by jump3r34** [comment]
Sounds like a plan, I could also see this utilizing AI if proper amounts of data were able to acquired in a semi-structured fashion.

**Comment by rpigu-i** [comment]
Cool. Take a look at the Python 3 branch, a few peeps are working on getting that stable. So feel free to create a branch off that and fix any bugs you find. Then create a PR against the python3 branch, when they are ready for merging.

**Comment by rpigu-i** [comment]
Going to close this issue since everyone is switching to the 3.x branch
