### ISSUE TITLE
skiptracer what can offer for ? graciously. favorably.

### ISSUE THREAD

**Issue by darknodi** [xillwillx/skiptracer#39]

**Comment by xillwillx** [comment]
if english is your second langauge, try using https://translate.google.com/ and come up with an intelligent question instead of these half-ass posts.

**Comment by darknodi** [comment]
Your Skiptracer product written in Python scripting, what can offer for me, what can do for me. 

@xillwillx

**Comment by xillwillx** [comment]
it can offer you a world of knoledge, try reading the readme.md

**Comment by darknodi** [comment]
Can you help me to take Google API Key and CX ID code for config.py ( PhoneInfoga ) 

Graciously millions.

**Comment by xillwillx** [comment]
if you want to pay for services. if not then learn yourself.

**Comment by darknodi** [comment]
@xillwillx your product script work in python3 with pip3 

or python and pip

**Comment by darknodi** [comment]
the modules needs credential key API.

**Comment by darknodi** [comment]
@xillwillx you are joy. 📦
