### ISSUE TITLE
Not able to use the script

### ISSUE THREAD

**Issue by desiklolan** [xillwillx/skiptracer#41]
Getting these error: urllib3 doesnt support urlencode function anymore. 

Error: tried both python & python3
root@kali:~/skiptracer# python skiptracer.py 
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/root/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/root/skiptracer/plugins/haveibeenpwned.py", line 13, in <module>
    import cfscrape
ImportError: No module named cfscrape
root@kali:~/skiptracer# python3 skiptracer.py 
No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/root/skiptracer/plugins/menus.py", line 13, in <module>
    from plugins.namechk2 import NameChkGrabber
  File "/root/skiptracer/plugins/namechk2.py", line 12, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.7/urllib/__init__.py)

**Comment by akintundejr4** [comment]
Having the same issues. I suggest setting up a virtual environment (venv) with Python 2 and running from there. I'm trying to get that set up right now.

**Comment by MTitley** [comment]
Having a similar issue. Receiving:

File "/skiptracer/plugins/knowem.py", line 8, in <module>
    from colors import BodyColors as bc
ModuleNotFoundError: No module named 'colors'

**Comment by akintundejr4** [comment]
> Having a similar issue. Receiving:
> 
> File "/skiptracer/plugins/knowem.py", line 8, in < module >
> from colors import BodyColors as bc
> ModuleNotFoundError: No module named 'colors'

I was able to get past this by running a Python 2.7.16 virtual environment (venv) and running Skip Tracer from there.

**Comment by rpigu-i** [comment]
The master branch currently contains 2.7 code. There is a Python 3 branch that is being worked on i.e. code is being migrated from 2.x to 3.x. Please feel free to help with the migration.
