### ISSUE TITLE
Module errors

### ISSUE THREAD

**Issue by xero-lib** [xillwillx/skiptracer#47]
Python 3:
```python
$ python skiptracer.py 
No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/helix/Scripts/skiptracer/plugins/menus.py", line 13, in <module>
    from plugins.namechk2 import NameChkGrabber
  File "/home/helix/Scripts/skiptracer/plugins/namechk2.py", line 12, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.8/urllib/__init__.py)
```
Python 2:
```python
$ python2 skiptracer.py 
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/helix/Scripts/skiptracer/plugins/menus.py", line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File "/home/helix/Scripts/skiptracer/plugins/fouroneone_info.py", line 5, in <module>
    from plugins.base import PageGrabber
  File "/home/helix/Scripts/skiptracer/plugins/base.py", line 4, in <module>
    import requests
ImportError: No module named requests
```

I followed the instructions, any idea what's going wrong?

Computer Info:
```
                   -`                    helix@vega 
                  .o+`                   ---------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: MS-7A78 1.0 
               `+oooooo:                 Kernel: 5.6.13-arch1-1 
               -+oooooo+:                Uptime: 1 day, 3 hours, 33 mins 
             `/:-:++oooo+:               Packages: 1775 (pacman), 45 (flatpak) 
            `/++++/+++++++:              Shell: bash 5.0.16 
           `/++++++++++++++:             Resolution: 1920x1080, 1920x1080, 1680x1050 
          `/+++ooooooooooooo/`           DE: GNOME 
         ./ooosssso++osssssso+`          WM: Mutter 
        .oossssso-````/ossssss+`         WM Theme: Adwaita 
       -osssssso.      :ssssssso.        Theme: Adwaita-dark [GTK2/3] 
      :osssssss/        osssso+++.       Icons: Adwaita [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: gnome-terminal 
   `/ossssso+/:-        -:/+osssso+-     CPU: Intel i7-7700K (8) @ 4.800GHz 
  `+sso+:-`                 `.-/+oso:    GPU: NVIDIA GeForce GTX 1060 3GB 
 `++:.                           `-/+/   Memory: 7599MiB / 15972MiB 
 .`                                 `/
                                                                 
                                                                 

```

**Comment by enochkasa** [comment]
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/root/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/root/skiptracer/plugins/haveibeenpwned.py", line 13, in <module>
    import cfscrape
ImportError: No module named cfscrape





                                   how can i fix it anyone telll me

**Comment by kpcyrd** [comment]
@xero-lib you're missing `python2-requests`
@enochkasa you're missing https://aur.archlinux.org/packages/python2-cfscrape/

**Comment by enochkasa** [comment]
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/root/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/root/skiptracer/plugins/haveibeenpwned.py", line 13, in <module>
    import cfscrape
ImportError: No module named cfscrape





                                   how can i fix it anyone telll me

**Comment by 74naUM2EMP** [comment]
@kpcyrd It looks like it can't find the requirements you install via `pip`, probably because they are the python3 versions. I tried to manually install the python2 versions which worked fine for `python2-requests` and `python2-lxml` but `python2-bs4` is only available from the AUR and it can't find this version of `bs4` even if you manually get it from the AUR -- `ImportError: No module named bs4`.

**Comment by mITYcIce** [comment]
> @xero-lib you're missing `python2-requests`
> @enochkasa you're missing https://aur.archlinux.org/packages/python2-cfscrape/

I've installed that but it doesn't seen to resolve the issue. Any other advice? Thanks!

**Comment by xxGeraldxx** [comment]
> > @xero-lib you're missing `python2-requests`
> > @enochkasa you're missing https://aur.archlinux.org/packages/python2-cfscrape/
> 
> I've installed that but it doesn't seen to resolve the issue. Any other advice? Thanks!

i also have the same issue. 
attempting 'python2 skiptracer.py' gives me the ImportError: No module named requests.
any suggestions? (using Kali Linux)

**Comment by Cisc0-gif** [comment]
having the same issue, it looks like a problem with the python2 to python3 conversion, tried installation steps with both versions and running with both but python2 says it can't install bs4 and python3 says it cant install urllib

**Comment by H4CK3RzHUB** [comment]
Traceback (most recent call last):
File "skiptracer.py", line 4, in
from plugins.menus import menus
File "/root/skiptracer/plugins/menus.py", line 12, in
from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
File "/root/skiptracer/plugins/haveibeenpwned.py", line 13, in
import cfscrape
ImportError: No module named cfscrape

@xillwillx nothing solves it

**Comment by AlecMcCutcheon** [comment]
it seems most of it is broken and needs to be updated lol

**Comment by 2thecurve** [comment]
Traceback (most recent call last):
  File "/root/skiptracer/skiptracer.py", line 4, in <module>
    from plugins.menus import menus
ModuleNotFoundError: No module named 'plugins'

**Comment by bryanlopezrr** [comment]
@C4l1b3r I get the exact same error

**Comment by SannanOfficial** [comment]
@C4l1b3r  I get the same error. Any fixes?

**Comment by ghost** [comment]
the main project description says it's being migrated from python2 to python3, there will be bugs, and to not report those types. it really needs to get a move on though. from his gitlab, he's more focused on hackthebox.

**Comment by spider863644** [comment]
Skiptracer is not working

**Comment by letmebeeeee** [comment]
do pip install -r requirements.txt           but sometimes that not always the case, see without femboys/faggots then we wouldn't have these scripts because of course rude mother fuckers know how to use these stuff, my point is if that don't work use "pip install module name"   example your missing cfscrape so put "pip install cfscrape".

**Comment by 2thecurve** [comment]
Man I had it working now I can't. Ugh

**Comment by deshawn124** [comment]
> wed the instructions, any idea what's going wrong?

Still no answers on these? or is there a new skiptracer in town?
