### ISSUE TITLE
Python3 issue

### ISSUE THREAD

**Issue by baqwas** [xillwillx/skiptracer#48]
Hello,

My apologies if this is redundant post and not an issue. I followed the installation steps on Ubuntu 20.04 desktop and there were no errors reported during the installation of **skiptracer**. Unfortunately, upon attempting to run the program for the 1st time, I encountered the following error:

`$ python3 skiptracer.py
No module named '__builtin__'
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/chowkidar/projects/skiptracer/plugins/menus.py", line 13, in <module>
    from plugins.namechk2 import NameChkGrabber
  File "/home/chowkidar/projects/skiptracer/plugins/namechk2.py", line 12, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode' from 'urllib' (/usr/lib/python3.8/urllib/__init__.py)
$ 
`
- I understand that the migration to python3 is either in progress or has been completed.
- I am not familiar with module namechk2
- I use module urllib in my introductory self-paced learning exercises

Guidance on overcoming the basic roadblock would be sincerely appreciated.

Kind regards.

**Comment by xillwillx** [comment]
the code is in the process of getting updated to python3 so youll have issues running as it is currently python2, stay tuned

**Comment by baqwas** [comment]
Thank you for the clarification.

Kind regards.
