### ISSUE TITLE
can someone tell me what I did wrong here? Please!

### ISSUE THREAD

**Issue by pegasu2020** [xillwillx/skiptracer#49]
python skiptracer.py
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/mai/skiptracer/plugins/menus.py", line 5, in <module>
    from plugins.fouroneone_info import FourOneOneGrabber
  File "/home/mai/skiptracer/plugins/fouroneone_info.py", line 5, in <module>
    from plugins.base import PageGrabber
  File "/home/mai/skiptracer/plugins/base.py", line 4, in <module>
    import requests
ImportError: No module named requests

**Comment by crankyadmin** [comment]
`ImportError: No module named requests`

Is requests installed? If you open a Python prompt and type `import requests`, did you pip install the requirements?

**Comment by glibglib3** [comment]
same problem
all requiements are satisfied 
still no luck
please help

**Comment by pastykid** [comment]
same issue

**Comment by kpcyrd** [comment]
Some distros already ship python3 as the default, try explicitly using python2:
```
pip2 install -r requirements.txt
```
and
```
python2 skiptracer.py
```

**Comment by mclaren675s** [comment]
Still not working it says pip2 not found

**Comment by opulentweed710** [comment]
not sure whats going but im getting this when typing 88 (Failed in report gen: [Errno 13] Permission denied: './skiptracer.docx'). any help please.

**Comment by kpcyrd** [comment]
> Still not working it says pip2 not found

This means you either have python3 pip or no pip at all. This is an issue on your end, the solution for this depends on the distro you're using.

**Comment by mclaren675s** [comment]
I’m using kali and can’t figure out how to get pip 2

**Comment by kpcyrd** [comment]
debian already dropped python2 pip, it seems kali still has it:
```
apt-get install python-pip
```

**Comment by mclaren675s** [comment]
It worked thanks so much!
