### ISSUE TITLE
Hacked-Emails Bad Res + advancedcheckbackground never run

### ISSUE THREAD

**Issue by iNoSec** [xillwillx/skiptracer#5]
Hi,

So first thing first i have no banner thats start directly on lookup prompt ;)

But the real problem is the Hacked Email who give me this error:
`Bad Res: list index out of range                                                
Bad Res: local variable 'trsplit' referenced before assignment `

And the AdvanceBackgroundChecks run for ever without output

**Comment by xillwillx** [comment]
post the command you're trying to use

**Comment by xillwillx** [comment]
also hacked-emails has changed their formatting and moved to ipv6, will look into it for next release

**Comment by iNoSec** [comment]
hello sir,

sry for the delay, i use `python skiptracer.py -l email `

and after that i have directly the prompt, not the banner and for hacked-email ihave 

`[?] Hacked-Emails
Bad Res: list index out of range
Bad Res: local variable 'trsplit' referenced before assignment
  [X] Attempting to get source, again ...
Bad Res: list index out of range
Bad Res: local variable 'trsplit' referenced before assignment
  [X] Attempting to get source, again ...
Bad Res: list index out of range
Bad Res: local variable 'trsplit' referenced before assignment
  [X] Attempting to get source, again ...
Bad Res: list index out of range
Bad Res: local variable 'trsplit' referenced before assignment
  [X] Attempting to get source, again ...
Bad Res: list index out of range
Bad Res: local variable 'trsplit' referenced before assignment
  [X] Failed at accessing site ... Try again later ...
`

But yeah i think there is something with hacked-emails because i have an other tools in python which produce error with them too

For the AdvanceBackgroundChecks i have no output at all after 30min running so i stop it.

Thanks for all, have a nice day

**Comment by pingywon** [comment]
Comment out the Hacked emails from the skiptracer.py for skippy to run correctly.

`#from plugins.hackedemails import HackedEmailGrabber`

If you just run:
`python skiptracer.py` 
you will get the banner you are looking for and than you can enter "phone|name|plate" etc.

If you run it with the "-l" (`python skiptracer.py -l`)  you will get the banner after it completes the query and returns the results.

**Comment by xillwillx** [comment]
hacked-emails changed their format to not offer lookups, it will email the person first. will be removed on version 2. for now as pingywon said comment it out. still checking on the advancedbackground issue.
