### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Misko2468** [xillwillx/skiptracer#51]
Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
  File "/home/kali/skiptracer/plugins/menus.py", line 12, in <module>
    from plugins.haveibeenpwned import HaveIBeenPwwnedGrabber
  File "/home/kali/skiptracer/plugins/haveibeenpwned.py", line 9, in <module>
    import simplejson as json
ImportError: No module named simplejson

I looked up the error & installed simplejson, but I'm sure I did it wrong & can't get help from StacksOF or find anything.

**Comment by AlecMcCutcheon** [comment]
![20200625_115604](https://user-images.githubusercontent.com/46252377/85754305-f2bfc000-b6da-11ea-8e01-4dcdfa822465.jpg)

**Comment by AlecMcCutcheon** [comment]
Hes also going to close this issue without even looking at it so its all pointless atm

**Comment by xillwillx** [comment]
> 
> 
> Hes also going to close this issue without even looking at it so its all pointless atm

right because: 
![image](https://user-images.githubusercontent.com/2845406/85755174-b17be000-b6db-11ea-8287-204ade5fa03d.png)

if you dont know how to read the readme then its pointless in wasting cycles. I do this for free, in my free time when I have time, I dont owe you anything. feel free to contribute if you want things done.

**Comment by AlecMcCutcheon** [comment]
I was just pointing out that it does not say that it is broken. it simply says you're moving it to python 3 people are spending hours trying to get it working and having no success and I would assume you wouldn't see as many open issues all the time from people if they knew it was pointless to try to get it to work right now. I'm aware you're doing this for free and greatly appreciate the work you've done up to this point. If you have a go fund me or whatnot I'd be happy to donate.

**Comment by AlecMcCutcheon** [comment]
@xillwillx I'll poke around some forums a bit and see what I can come up with for getting you more contributors

**Comment by FATCAT47** [comment]
from plugins.colors import BodyColors as bc
ModuleNotFoundError: No module named 'plugins.colors'

**Comment by xillwillx** [comment]
@AlecMcCutcheon  Do you eat paintchips

**Comment by nickvorie** [comment]
Yeah, can we get an install guide that works? 

Getting the error:
```
ERROR: Could not find a version that satisfies the requirement ipython==7.16.1 (from -r requirements.txt (line 12)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0)
ERROR: No matching distribution found for ipython==7.16.1 (from -r requirements.txt (line 12))
```

**Comment by Alexandros-Kordatzakis** [comment]
> Yeah, can we get an install guide that works? 
> 
> 
> 
> Getting the error:
> 
> ```
> 
> ERROR: Could not find a version that satisfies the requirement ipython==7.16.1 (from -r requirements.txt (line 12)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0)
> 
> ERROR: No matching distribution found for ipython==7.16.1 (from -r requirements.txt (line 12))
> 
> ```

For real, can't you read the README...?!

https://user-images.githubusercontent.com/2845406/85755174-b17be000-b6db-11ea-8287-204ade5fa03d.png
