### ISSUE TITLE
Issue starting skiptracer.py

### ISSUE THREAD

**Issue by Samuel20354** [xillwillx/skiptracer#56]
so i started skiptracer.py with python3 and python2 and it keeps saying:

Traceback (most recent call last):
  File "skiptracer.py", line 4, in <module>
    from plugins.menus import menus
ImportError: No module named plugins.menus

I have installed the requirements.txt file and followed the tutorial correctly and it don't work pls help

**Comment by Setsen7** [comment]
having the same issue. aggravating. i cant seem to correct it no matter what i do

**Comment by Setsen7** [comment]
ah. if you look at the closed issues, this is normal. the readme doesnt specify that it doesnt work at all right now, just that its being ported to python3. could be more descriptive, but its not going to work right now it seems

**Comment by Samuel20354** [comment]
> ah. if you look at the closed issues, this is normal. the readme doesnt specify that it doesnt work at all right now, just that its being ported to python3. could be more descriptive, but its not going to work right now it seems

Oh ok thanks for the help

**Comment by Samuel20354** [comment]
Do you know when the the skiptracer is going to start working.

**Comment by Alexandros-Kordatzakis** [comment]
> Do you know when the the skiptracer is going to start working.

Nobody does. 
The author clearly states that it's a W.I.P. to support Python 3, and that the previous Python 2 versions weren't working. We wait until then..!

**Comment by Samuel20354** [comment]
okayy thanks for the help and info.

**Comment by Setsen7** [comment]
Samuel, the other day i found a version that still worked with py2. Just use the search bar and search skiptracer, some random user has an old working version posted. Dunno if this is allowed, so illwill, delete this comment if you must
