### ISSUE TITLE
Issue upon installation on Kali Linux

### ISSUE THREAD

**Issue by chrismin217** [xillwillx/skiptracer#59]
I get this error message after running the command 

sudo pip install -r requirements.txt

===

ERROR: Could not find a version that satisfies the requirement ipython==7.16.1 (from -r requirements.txt (line 12)) (from versions: 0.10, 0.10.1, 0.10.2, 0.11, 0.12, 0.12.1, 0.13, 0.13.1, 0.13.2, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 3.0.0, 3.1.0, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 4.0.0b1, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.1.0rc1, 4.1.0rc2, 4.1.0, 4.1.1, 4.1.2, 4.2.0, 4.2.1, 5.0.0b1, 5.0.0b2, 5.0.0b3, 5.0.0b4, 5.0.0rc1, 5.0.0, 5.1.0, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.4.0, 5.4.1, 5.5.0, 5.6.0, 5.7.0, 5.8.0, 5.9.0, 5.10.0)                                                 
ERROR: No matching distribution found for ipython==7.16.1 (from -r requirements.txt (line 12))

**Comment by cyborg411** [comment]
Same for me, i think it's because python2 is not supported anymore ..

**Comment by Alexandros-Kordatzakis** [comment]
![Screenshot_531](https://user-images.githubusercontent.com/32456971/89032403-4017f880-d33d-11ea-9834-664050cad407.png)

Why is it so hard for people to read a(n), Already open, README file?
